"""stage 07 signal + regime columns

Revision ID: 28ce6e20dc36
Revises: cdfa304ff896
Create Date: 2026-05-01 07:55:11.442271
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28ce6e20dc36"
down_revision: str | None = "cdfa304ff896"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Columns (autogenerated)
    op.add_column("regime_snapshots", sa.Column("regime", sa.String(length=30), nullable=True))
    op.add_column(
        "regime_snapshots", sa.Column("signal_posture", sa.String(length=20), nullable=True)
    )
    op.add_column("regime_snapshots", sa.Column("confidence", sa.Integer(), nullable=True))
    op.add_column(
        "regime_snapshots",
        sa.Column("reasoning", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("signals", sa.Column("price_source", sa.String(length=20), nullable=True))
    op.add_column(
        "signals",
        sa.Column("ai_prompt_version", sa.String(length=10), server_default="v1", nullable=False),
    )

    # CHECK constraints (Alembic autogen does not detect these; added manually).
    op.create_check_constraint(
        "ck_regime_snapshots_regime_enum",
        "regime_snapshots",
        "regime IS NULL OR regime IN "
        "('accumulation','markup','distribution','markdown','uncertain')",
    )
    op.create_check_constraint(
        "ck_regime_snapshots_posture_enum",
        "regime_snapshots",
        "signal_posture IS NULL OR signal_posture IN ('aggressive','normal','cautious','paused')",
    )
    op.create_check_constraint(
        "ck_regime_snapshots_confidence_range",
        "regime_snapshots",
        "confidence IS NULL OR confidence BETWEEN 1 AND 10",
    )
    op.create_check_constraint(
        "ck_signals_ai_prompt_version_format",
        "signals",
        "ai_prompt_version ~ '^v[0-9]+$'",
    )


def downgrade() -> None:
    op.drop_constraint("ck_signals_ai_prompt_version_format", "signals", type_="check")
    op.drop_constraint("ck_regime_snapshots_confidence_range", "regime_snapshots", type_="check")
    op.drop_constraint("ck_regime_snapshots_posture_enum", "regime_snapshots", type_="check")
    op.drop_constraint("ck_regime_snapshots_regime_enum", "regime_snapshots", type_="check")
    op.drop_column("signals", "ai_prompt_version")
    op.drop_column("signals", "price_source")
    op.drop_column("regime_snapshots", "reasoning")
    op.drop_column("regime_snapshots", "confidence")
    op.drop_column("regime_snapshots", "signal_posture")
    op.drop_column("regime_snapshots", "regime")
