"""branch_02_delivery_retry_columns — add SignalDelivery.last_attempt_at

Adds the column that powers exponential-backoff retries on transient
Telegram errors. Nullable because (a) it's NULL for rows created before
this migration ran, and (b) NULL is the natural "never attempted" state
for fresh rows post-migration.

The companion model change `attempt_count.default = 1 → 0` is a Python-
side ORM default applied at INSERT time, NOT a server-side DEFAULT —
so it requires no DB schema change. Existing rows keep their old
attempt_count (the 8 FAILED rows from the pre-fix incident and the 18
DELIVERED rows all carry count=2 from the legacy +1-on-attempt semantic);
the cap check (`count >= delivery_max_attempts`) gives them roughly the
same retry budget as new rows.

Revision ID: cc33875641da
Revises: f2c95b75d375
Create Date: 2026-05-12 13:26:05.818316
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc33875641da"
down_revision: str | None = "f2c95b75d375"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signal_deliveries", sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal_deliveries", "last_attempt_at")
    # ### end Alembic commands ###
