"""initial schema

Revision ID: cdfa304ff896
Revises:
Create Date: 2026-04-22 08:09:20.927608
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdfa304ff896"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuit_breakers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("trigger_type", sa.String(length=50), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuit_breakers")),
    )
    op.create_table(
        "etf_flows",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("captured_at", sa.Date(), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("total_net_flow_usd", sa.Numeric(), nullable=False),
        sa.Column("total_value_traded", sa.Numeric(), nullable=True),
        sa.Column("total_net_assets", sa.Numeric(), nullable=True),
        sa.Column("cum_net_inflow", sa.Numeric(), nullable=True),
        sa.Column("per_etf_flows", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_etf_flows")),
    )
    op.create_index("ix_etf_flows_asset_date", "etf_flows", ["asset", "captured_at"], unique=True)
    op.create_table(
        "news_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("category", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
        sa.UniqueConstraint("source_id", name=op.f("uq_news_items_source_id")),
    )
    op.create_index(
        "ix_news_category_date", "news_items", ["category", "captured_at"], unique=False
    )
    op.create_index(
        "ix_news_currencies", "news_items", ["currencies"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "regime_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("btc_dominance", sa.Numeric(), nullable=True),
        sa.Column("flow_trend_7d", sa.Numeric(), nullable=True),
        sa.Column("macro_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("news_velocity", sa.Integer(), nullable=True),
        sa.Column("ai_interpretation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regime_snapshots")),
    )
    op.create_index("ix_regime_captured", "regime_snapshots", ["captured_at"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("signal_type", sa.String(length=30), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("trigger_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("price_at_creation", sa.Numeric(), nullable=True),
        sa.Column("fingerprint", sa.String(length=32), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alerted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 1 AND 10", name="ck_signals_confidence_range"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index("ix_signals_asset_created", "signals", ["asset", "created_at"], unique=False)
    op.create_index("ix_signals_created", "signals", ["created_at"], unique=False)
    op.create_index("ix_signals_expires", "signals", ["expires_at"], unique=False)
    op.create_index(
        "ix_signals_fingerprint_date", "signals", ["fingerprint", "signal_date"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("tier_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agreed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("pref_assets", postgresql.ARRAY(sa.String(length=10)), nullable=False),
        sa.Column("pref_min_confidence", sa.Integer(), nullable=False),
        sa.Column("pref_paused", sa.Boolean(), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pref_min_confidence BETWEEN 1 AND 10", name="ck_users_pref_min_confidence_range"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_delivery",
        "users",
        ["is_active", "pref_paused", "pref_min_confidence"],
        unique=False,
    )
    op.create_index(
        "ix_users_pref_assets", "users", ["pref_assets"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_users_tier", "users", ["tier", "tier_expires_at"], unique=False)
    op.create_table(
        "notification_channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_type", sa.String(length=20), nullable=False),
        sa.Column("channel_identifier", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_channels_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channels")),
    )
    op.create_index(
        "ix_channels_lookup",
        "notification_channels",
        ["channel_type", "channel_identifier"],
        unique=False,
    )
    op.create_index(
        "ix_channels_unique",
        "notification_channels",
        ["channel_type", "channel_identifier"],
        unique=True,
    )
    op.create_index(
        "ix_channels_user_active",
        "notification_channels",
        ["user_id", "channel_type", "is_active"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("signal_id", sa.BigInteger(), nullable=True),
        sa.Column("venue", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("order_type", sa.String(length=10), nullable=False),
        sa.Column("time_in_force", sa.String(length=10), nullable=False),
        sa.Column("requested_size", sa.Numeric(), nullable=False),
        sa.Column("requested_price", sa.Numeric(), nullable=True),
        sa.Column("filled_size", sa.Numeric(), nullable=True),
        sa.Column("filled_price", sa.Numeric(), nullable=True),
        sa.Column("filled_value", sa.Numeric(), nullable=True),
        sa.Column("fees", sa.Numeric(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=100), nullable=True),
        sa.Column("client_order_id", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_orders_signal_id_signals")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("client_order_id", name=op.f("uq_orders_client_order_id")),
    )
    op.create_index("ix_orders_exchange", "orders", ["exchange_order_id"], unique=False)
    op.create_index("ix_orders_signal", "orders", ["signal_id"], unique=False)
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    op.create_index("ix_orders_user", "orders", ["user_id"], unique=False)
    op.create_table(
        "signal_outcomes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("signal_type", sa.String(length=30), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(), nullable=True),
        sa.Column("stop_price", sa.Numeric(), nullable=True),
        sa.Column("target_price", sa.Numeric(), nullable=True),
        sa.Column("price_at_signal", sa.Numeric(), nullable=False),
        sa.Column("price_after_24h", sa.Numeric(), nullable=True),
        sa.Column("price_after_72h", sa.Numeric(), nullable=True),
        sa.Column("hit_target", sa.Boolean(), nullable=True),
        sa.Column("hit_stop", sa.Boolean(), nullable=True),
        sa.Column("max_favorable", sa.Numeric(), nullable=True),
        sa.Column("max_adverse", sa.Numeric(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confidence BETWEEN 1 AND 10", name="ck_outcomes_confidence_range"),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_signal_outcomes_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_outcomes")),
        sa.UniqueConstraint("signal_id", name=op.f("uq_signal_outcomes_signal_id")),
    )
    op.create_index("ix_outcomes_evaluated", "signal_outcomes", ["evaluated_at"], unique=False)
    op.create_index(
        "ix_outcomes_track_record",
        "signal_outcomes",
        ["asset", "signal_type", "hit_target"],
        unique=False,
    )
    op.create_table(
        "telegram_groups",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("added_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("tier_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("pref_assets", postgresql.ARRAY(sa.String(length=10)), nullable=False),
        sa.Column("pref_min_confidence", sa.Integer(), nullable=False),
        sa.Column("pref_paused", sa.Boolean(), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pref_min_confidence BETWEEN 1 AND 10", name="ck_groups_pref_min_confidence_range"
        ),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"],
            ["users.id"],
            name=op.f("fk_telegram_groups_added_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_groups")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_telegram_groups_chat_id")),
    )
    op.create_index(
        "ix_groups_delivery", "telegram_groups", ["is_active", "tier", "pref_paused"], unique=False
    )
    op.create_index(
        "ix_groups_pref_assets",
        "telegram_groups",
        ["pref_assets"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_telegram_groups_added_by_user_id"),
        "telegram_groups",
        ["added_by_user_id"],
        unique=False,
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("signal_id", sa.BigInteger(), nullable=True),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("venue", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("size", sa.Numeric(), nullable=False),
        sa.Column("entry_price", sa.Numeric(), nullable=False),
        sa.Column("stop_loss", sa.Numeric(), nullable=True),
        sa.Column("take_profit", sa.Numeric(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_price", sa.Numeric(), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_positions_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_positions_signal_id_signals")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_positions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index("ix_positions_order", "positions", ["order_id"], unique=False)
    op.create_index("ix_positions_signal", "positions", ["signal_id"], unique=False)
    op.create_index("ix_positions_status", "positions", ["status"], unique=False)
    op.create_index("ix_positions_user", "positions", ["user_id"], unique=False)
    op.create_table(
        "signal_deliveries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND group_id IS NULL AND channel_id IS NOT NULL) OR (user_id IS NULL AND group_id IS NOT NULL AND channel_id IS NULL)",
            name="ck_delivery_target",
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channels.id"],
            name=op.f("fk_signal_deliveries_channel_id_notification_channels"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["telegram_groups.id"],
            name=op.f("fk_signal_deliveries_group_id_telegram_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_signal_deliveries_signal_id_signals")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_signal_deliveries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_deliveries")),
    )
    op.create_index("ix_delivery_cleanup", "signal_deliveries", ["created_at"], unique=False)
    op.create_index(
        "ix_delivery_group", "signal_deliveries", ["group_id", "created_at"], unique=False
    )
    op.create_index("ix_delivery_pending", "signal_deliveries", ["status"], unique=False)
    op.create_index("ix_delivery_signal", "signal_deliveries", ["signal_id"], unique=False)
    op.create_index(
        "ix_delivery_user", "signal_deliveries", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "ux_delivery_group_signal",
        "signal_deliveries",
        ["signal_id", "group_id"],
        unique=True,
        postgresql_where=sa.text("group_id IS NOT NULL"),
    )
    op.create_index(
        "ux_delivery_user_signal",
        "signal_deliveries",
        ["signal_id", "user_id", "channel_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_delivery_user_signal",
        table_name="signal_deliveries",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "ux_delivery_group_signal",
        table_name="signal_deliveries",
        postgresql_where=sa.text("group_id IS NOT NULL"),
    )
    op.drop_index("ix_delivery_user", table_name="signal_deliveries")
    op.drop_index("ix_delivery_signal", table_name="signal_deliveries")
    op.drop_index("ix_delivery_pending", table_name="signal_deliveries")
    op.drop_index("ix_delivery_group", table_name="signal_deliveries")
    op.drop_index("ix_delivery_cleanup", table_name="signal_deliveries")
    op.drop_table("signal_deliveries")
    op.drop_index("ix_positions_user", table_name="positions")
    op.drop_index("ix_positions_status", table_name="positions")
    op.drop_index("ix_positions_signal", table_name="positions")
    op.drop_index("ix_positions_order", table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_telegram_groups_added_by_user_id"), table_name="telegram_groups")
    op.drop_index("ix_groups_pref_assets", table_name="telegram_groups", postgresql_using="gin")
    op.drop_index("ix_groups_delivery", table_name="telegram_groups")
    op.drop_table("telegram_groups")
    op.drop_index("ix_outcomes_track_record", table_name="signal_outcomes")
    op.drop_index("ix_outcomes_evaluated", table_name="signal_outcomes")
    op.drop_table("signal_outcomes")
    op.drop_index("ix_orders_user", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_signal", table_name="orders")
    op.drop_index("ix_orders_exchange", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_channels_user_active", table_name="notification_channels")
    op.drop_index("ix_channels_unique", table_name="notification_channels")
    op.drop_index("ix_channels_lookup", table_name="notification_channels")
    op.drop_table("notification_channels")
    op.drop_index("ix_users_tier", table_name="users")
    op.drop_index("ix_users_pref_assets", table_name="users", postgresql_using="gin")
    op.drop_index("ix_users_delivery", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_signals_fingerprint_date", table_name="signals")
    op.drop_index("ix_signals_expires", table_name="signals")
    op.drop_index("ix_signals_created", table_name="signals")
    op.drop_index("ix_signals_asset_created", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_regime_captured", table_name="regime_snapshots")
    op.drop_table("regime_snapshots")
    op.drop_index("ix_news_currencies", table_name="news_items", postgresql_using="gin")
    op.drop_index("ix_news_category_date", table_name="news_items")
    op.drop_table("news_items")
    op.drop_index("ix_etf_flows_asset_date", table_name="etf_flows")
    op.drop_table("etf_flows")
    op.drop_table("circuit_breakers")
    # ### end Alembic commands ###
